[pytest]
testpaths = tests
asyncio_mode = auto
filterwarnings =
    error::pytest.PytestReturnNotNoneWarning
    error::sklearn.exceptions.InconsistentVersionWarning
    ignore:tagMap is deprecated\. Please use TAG_MAP instead\.:DeprecationWarning:ldap3\.utils\.asn1
    ignore:typeMap is deprecated\. Please use TYPE_MAP instead\.:DeprecationWarning:ldap3\.utils\.asn1
    ignore:Inheritance class AiohttpClientSession from ClientSession is discouraged:DeprecationWarning:google\.genai\._api_client
